"""Excel export of chat answers (tables become formatted sheets)."""

import io
import re
from datetime import datetime

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from app.schemas import ExportRequest

HEADER_FILL = PatternFill("solid", fgColor="1F6FE5")
HEADER_FONT = Font(bold=True, color="FFFFFF")
THIN = Side(style="thin", color="D5DEEA")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
NUMBER = re.compile(r"^\s*(?:₹|rs\.?|inr)?\s*(-?[\d,]*\.?\d+)\s*(%)?\s*$", re.IGNORECASE)
DISCLAIMER = (
    "Generated by DMFT Sahayak from official DMFT Uttar Bastar Kanker documents. "
    "Verify important figures with the DMFT office before official use."
)


def _cell_value(value):
    """Numbers stay numbers in Excel ('1,200' -> 1200, '70%' -> 0.7 formatted as %)."""
    if isinstance(value, (int, float)) or value is None:
        return value, None
    match = NUMBER.match(str(value))
    if not match:
        return str(value), None
    number = float(match.group(1).replace(",", ""))
    if match.group(2):
        return number / 100, "0.##%"
    return (int(number) if number.is_integer() else number), "#,##0.##"


def _sheet_name(title: str, used: set[str], index: int) -> str:
    base = re.sub(r"[\[\]:*?/\\]", " ", title).strip()[:28] or f"Table {index}"
    name, n = base, 2
    while name.lower() in used:
        name, n = f"{base[:25]} {n}", n + 1
    used.add(name.lower())
    return name


def _plain(markdown: str) -> str:
    text = re.sub(r"```chart.*?```", "", markdown, flags=re.S)
    text = re.sub(r"^\s*\|.*\|\s*$", "", text, flags=re.M)
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()


def build_workbook(request: ExportRequest) -> bytes:
    workbook = Workbook()
    summary = workbook.active
    summary.title = "Summary"
    summary.column_dimensions["A"].width = 18
    summary.column_dimensions["B"].width = 100
    rows = [
        ("DMFT Sahayak", request.title),
        ("Question", request.question),
        ("Generated", datetime.now().strftime("%d %b %Y, %H:%M")),
        ("Answer", _plain(request.answer)),
        ("Sources", "\n".join(request.sources)),
        ("Note", DISCLAIMER),
    ]
    for row_index, (label, value) in enumerate(rows, start=1):
        summary.cell(row=row_index, column=1, value=label).font = Font(bold=True)
        cell = summary.cell(row=row_index, column=2, value=value)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
    summary["B1"].font = Font(bold=True, size=13)

    used: set[str] = {"summary"}
    for index, table in enumerate(request.tables, start=1):
        sheet = workbook.create_sheet(_sheet_name(table.title, used, index))
        widths = [len(str(h)) for h in table.headers]
        for col, header in enumerate(table.headers, start=1):
            cell = sheet.cell(row=1, column=col, value=header)
            cell.fill, cell.font, cell.border = HEADER_FILL, HEADER_FONT, BORDER
            cell.alignment = Alignment(wrap_text=True, vertical="center")
        for row_index, row in enumerate(table.rows, start=2):
            for col, raw in enumerate(row[: len(table.headers)], start=1):
                value, number_format = _cell_value(raw)
                cell = sheet.cell(row=row_index, column=col, value=value)
                cell.border = BORDER
                if number_format:
                    cell.number_format = number_format
                if col - 1 < len(widths):
                    widths[col - 1] = max(widths[col - 1], len(str(raw or "")))
        for col, width in enumerate(widths, start=1):
            sheet.column_dimensions[get_column_letter(col)].width = min(max(width + 2, 10), 60)
        sheet.freeze_panes = "A2"

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()
